config/routes.rb
Blog::Application.routes.draw do
	devise_for :users

	resources :posts do
		resources :comments
	end

	root "posts#index"
	get '/about', to: 'pages#about'
	get '/contact', to: 'pages#contact'
	get 'tags/:tag', to: 'posts#index', as: :tag

	devise_scope :user do
		get "/admin" => "devise/sessions#new"
	end

	match '/contacts',     to: 'contacts#new',             via: 'get'
	resources "contacts", only: [:new, :create]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	validates :name, presence: true, length: {minimum: 3}
	validates :body, presence: true, length: {minimum: 5}
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "giedrius.rimkus.a@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true
	acts_as_taggable_on :tags

	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged

	def slug_candidates
	  [[:id, :title]]
	end

	def should_generate_new_friendly_id?
		new_record?
	end

	def previous_post
  		self.class.first(:conditions => ["created_at < ?", created_at], :order => "created_at desc")
	end

	def next_post
  		self.class.first(:conditions => ["created_at > ?", created_at], :order => "created_at asc")
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		@comment = Comment.new
	end

	def create
		@post = Post.friendly.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))
		# redirect_to post_path(@post)
		
		# if @comment.errors.any?
  		#	render 'new'
		# else
  		#	redirect_to @post
		# end

		if @comment.save
      		flash[:success] = "Your comment has been succesfully submited! Thank you."
      		redirect_to post_path(@post)
    	else
    		# flash[:danger] = "Oops... Something went wrong. Please try again."
      		render 'new'
      		# redirect_to post_path(@post)
    	end
	end

	def destroy
		@post = Post.friendly.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
        flash[:success] = "Comment deleted."
		redirect_to post_path(@post)
	end

	def edit
		@post = Post.friendly.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def update
		@post = Post.friendly.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

		if @comment.update(comments_params)
			redirect_to post_url(@post)
			flash[:success] = "Comment updated."
		else
			flash[:danger] = "Oops... Something went wrong."
			render 'edit'
		end
	end
	
	private

	def comments_params
		params.require(:comment).permit(:name, :body)
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Your message has been sent. Thank you!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		if params[:tag]
			@posts = Post.tagged_with(params[:tag]).order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
		else
			@posts = Post.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
		end
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			flash[:success] = "Your post has been successfully submitted!"
			redirect_to @post
		else
			flash[:danger] = "Oops... Something went wrong. "
			render 'new'
		end
	end

	def show
		@post = Post.friendly.find(params[:id])
		# @comment = @post.comments.build
	end

	def edit
		@post = Post.friendly.find(params[:id]) 
	end

	def update
		@post = Post.friendly.find(params[:id])

		if @post.update(params[:post].permit(:title, :body, :author, :tag_list))
			redirect_to @post
			flash[:success] = "Post has been updated."
		else
			flash[:danger] = "Oops... Something went wrong. "
			render 'edit'
		end
	end

	def destroy
		@post = Post.friendly.find(params[:id])
		@post.destroy
		flash[:success] = "Post has been deleted."
		redirect_to root_path
	end


	private

	def post_params
		params.require(:post).permit(:title, :body, :tag_list, :author)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>	
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>

	<% if current_user.try(:admin?) %>
		<div class="buttons">
			<button class="button"><span class="glyphicon glyphicon-remove"></span><%= link_to 'Delete', [comment.post, comment],
							method: :delete,
							data: { confirm: "Are you sure?" } %>
			</button>
			<button class="button"><span class="glyphicon glyphicon-edit"><%= link_to 'Edit',  edit_post_comment_path(@post, comment) %></button>
		</div>
	<% end %>
</div>

app/views/comments/_comment_form.html.erb
<%= form_for([@post, @comment]) do |f| %>

	<% if @comment.errors.any? %>
			<div class="alert alert-danger" role="alert">
				<h2><%= pluralize(@comment.errors.count, "error") %> prevented this from saving:</h2>
				<ul>
					<% @comment.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
	<% end %>

<p>
	<%= f.label :name, "Your Name: " %><br>
	<%= f.text_field :name %>
</p>

<p>
	<%= f.label :body,  "Comment: " %><br>
	<%= f.text_area :body %>
</p>
<br>

<p><%= f.submit %></p>

<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

<p>
	<%= f.label :name, "Your Name: " %><br>
	<%= f.text_field :name %>
</p>

<p>
	<%= f.label :body, "Comment: " %><br>
	<%= f.text_area :body %>
</p>
<br>

<p><%= f.submit %></p>

<% end %>

app/views/comments/edit.html.erb
<div id="page_wrapper">
	<h3>Edit comment</h3>
	<%= render :partial => 'comment_form' %>
</div>

app/views/comments/new.html.erb
<div id="page_wrapper">
	<h2>Add New Comment</h2>
	<%= render 'comment_form' %>
</div>

app/views/comments/show.html.erb
<div id="post_content">
	<h1 class="title">
		Title
	</h1>

	<p class="date">
		
		<% if user_signed_in? %>
		<p>Buttonai</p>
		<% end %>
	</p>
	<p class="body">
	<%= render 'comments/edit' %>
	</p>
	<div id="comments">
		<h2>Comments</h2>
		<h3>Add a comment:</h3>
	</div>
</div>

app/views/comments/test-show.html.erb
<div id="post_content">
	<h1 class="title">
		Title
	</h1>

	<p class="date">
		
		<% if user_signed_in? %>
		<p>Buttonai</p>
		<% end %>
	</p>
	<p class="body">
	<%= render 'comments/edit' %>
	</p>
	<div id="comments">
		<h2>Comments</h2>
		<h3>Add a comment:</h3>
	</div>
</div>

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <h3>Send me a message</h3>
  <br>
  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>


  <% if @contact.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <h2><%= pluralize(@contact.errors.count, "error") %> prevented this from sending:</h2>
        <ul>
          <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>


    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "button" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %>Giedrius Rimkus</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

<style>
</style>
</head>
<body>
	<div id="sidebar">
		<ul>
			<%= link_to root_path do %>
			<%= image_tag "logo.png" %>
			<% end %>
			<p> </p>
			<!-- <li class="category">Website</li> -->
			<li><%= link_to root_path do %>
				<span class="glyphicon glyphicon-home"></span>&nbsp;Home
				<% end %>
			</li>
			<li><%= link_to about_path do %>
				<span class="glyphicon glyphicon-user"></span>&nbsp;About
				<% end %>
			</li>
			<li><%= link_to contacts_path do %>
				<span class="glyphicon glyphicon-envelope"></span>&nbsp;Contacts
				<% end %>
			</li>
		</ul>

		<!-- <ul>
			<li class="category">Social</li>
			<li>Facebook</li>
			<li>Twitter</li>
			<li>Github</li>
		</ul> 
		<ul>
			<li class="category"></span> Tags</li>
			<li><div class="tag_cloud">
			<p>
			<% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
			<%= raw link_to tag.name, tag_path(tag.name), class: css_class %>
			<% end %>
			</p>
			</div></li>
		</ul>-->
	</div>

	<div id="main_content">
		<div id="header">

			<% if current_page?(root_path) %>
				<p>All Posts</p>
			<% elsif current_page?(about_path)%>
				<p>About</p>
			<% else %>
				<%= link_to "Back to All Posts", root_path %>
			<% end %>

				<div class="buttons">
					<% if current_user.try(:admin?)  %>
					<button class="button"><span class="glyphicon glyphicon-file"></span> <%= link_to "New Post", new_post_path %></button> <% end %>
					<% if user_signed_in?  %>
					<button class="button"><span class="glyphicon glyphicon-user"></span> <%= link_to "Profile", edit_user_registration_path %></button>
					<button class="button"><span class="glyphicon glyphicon-off"></span> <%= link_to "Logout", destroy_user_session_path, :method => :delete %></button>
				<% end %>
				</div>
		</div>
		<%= render 'posts/flash' %>
		<%= yield %>
	</div>

</body>
</html>

app/views/layouts/test-application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %>Giedrius Rimkus</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Custom Fonts -->
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

</head>
<body>

<div class="blog-masthead">
	<div class="container">
		<nav class="blog-nav">
			<a class="blog-nav-item active" href="#">Home</a>
			<a class="blog-nav-item" href="#">New features</a>
			<a class="blog-nav-item" href="#">Press</a>
			<a class="blog-nav-item" href="#">New hires</a>
			<a class="blog-nav-item" href="#">About</a>
		</nav>
	</div>
</div>

	<div id="sidebar">
		<ul>
			<%= link_to root_path do %>
			<%= image_tag "logo.png" %>
			<% end %>
			<p> </p>
			<!-- <li class="category">Website</li> -->
			<li><%= link_to root_path do %>
				<span class="glyphicon glyphicon-home"></span>&nbsp;Home
				<% end %>
			</li>
			<li><%= link_to about_path do %>
				<span class="glyphicon glyphicon-user"></span>&nbsp;About
				<% end %>
			</li>
			<li><%= link_to contacts_path do %>
				<span class="glyphicon glyphicon-envelope"></span>&nbsp;Contacts
				<% end %>
			</li>
		</ul>
		<!-- <ul>
			<li class="category">Social</li>
			<li>Facebook</li>
			<li>Twitter</li>
			<li>Github</li>
		</ul> 
		<ul>
			<li class="category"></span> Tags</li>
			<li><div class="tag_cloud">
			<p>
			<% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
			<%= raw link_to tag.name, tag_path(tag.name), class: css_class %>
			<% end %>
			</p>
			</div></li>
		</ul>-->
	</div>

	<div id="main_content">
		<div id="header">

			<% if current_page?(root_path) %>
				<p>All Posts</p>
			<% elsif current_page?(about_path)%>
				<p>About</p>
			<% else %>
				<%= link_to "Back to All Posts", root_path %>
			<% end %>

				<div class="buttons">
					<% if current_user.try(:admin?)  %>
					<button class="button"><span class="glyphicon glyphicon-file"></span> <%= link_to "New Post", new_post_path %></button> <% end %>
					<% if user_signed_in?  %>
					<button class="button"><span class="glyphicon glyphicon-user"></span> <%= link_to "Profile", edit_user_registration_path %></button>
					<button class="button"><span class="glyphicon glyphicon-off"></span> <%= link_to "Logout", destroy_user_session_path, :method => :delete %></button>
				<% end %>
				</div>
		</div>
		<%= render 'posts/flash' %>
		<%= yield %><!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <h1>Hello, world!</h1>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About Me | ") %>
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "profile.jpeg" %>
	</div>
	
	<div id="content">
		<h1>Hello.</h1>
		<p>My name is Giedrius. I am super cool.</p>
	</div>
</div>

app/views/pages/contact.html.erb
<% provide(:title, "Contact Me | ") %>
<div id="page_wrapper">
	<div id="content">
		<h1>Contact Me</h1>
		<p>Contacts form</p>
	</div>
</div>

app/views/posts/_flash.html.erb
<div>
<% flash.each do |message_type, message| %>
	  	<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
	<% end %>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	
	<% if @post.errors.any? %>
		<div class="alert alert-danger" role="alert">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this from saving:</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="row">
  	<div class="">
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :author %><br>
		<%= f.text_field :author %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= raw f.text_area :body, class: "tinymce" %>
	</p>
	<p>
		<%= f.label :tags, "Tags (separated by commas)" %><br>
		<%= f.text_field :tag_list %>
	</p>
	<p>
		<%= f.submit "Submit Post", class: "" %>
	</p>
	</div>
	</div>
	<% end %>
	<%= tinymce %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h2>Edit Post</h2>
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="post_wrapper">
	<h2 class="title"><%= link_to post.title, post %></h2>
	<p class="date_and_author"><span class="glyphicon glyphicon-time"></span>
	<%= post.created_at.strftime("%B, %d, %Y") %>
	<% if post.author? %>&nbsp;&nbsp;
    <span class="glyphicon glyphicon-user"></span>
    <%= post.author  %> 
    <% end %> 
    &nbsp;&nbsp;<span class="glyphicon glyphicon-comment"></span> Comments: <%= link_to post.comments.count, post_path(post, anchor: "show-comments") %></a>
	</p>
	<p class="body"><%= raw post.body %></p>
	<p class="number_of_comments"></p>
	<% if post.tag_list.any? %>
	<p class="tags"><span class="glyphicon glyphicon-tags">&nbsp;</span><%= raw post.tag_list.map { |tag| link_to tag, tag_path(tag) }.join(', ') %></p>
	<% end %>
</div>
<% end %>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h2>Compose New Post</h2>
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title">
		<%= @post.title %>
	</h1>
	
	<p class="date_and_author"><span class="glyphicon glyphicon-time"></span>
	<%= @post.created_at.strftime("%B, %d, %Y") %>
	<% if @post.author? %>&nbsp;&nbsp;
    <span class="glyphicon glyphicon-user"></span>
    <%= @post.author %> 
    <% end %> 
    &nbsp;&nbsp;<span class="glyphicon glyphicon-comment"></span>&nbsp;Comments: <a href="#show-comments"><%= @post.comments.count %></a>
	</p>
	
	<% if current_user.try(:admin?) %>
		<div class="buttons">
			<button class="btn btn-primary">
			<span class="glyphicon glyphicon-edit"></span>&nbsp;<%= link_to ' Edit  ', edit_post_path(@post) %></button>
			<button class="btn btn-danger"> 
			<span class="glyphicon glyphicon-remove"></span>&nbsp;<%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
			</button>
		</div>
	<% end %>

	<p class="body">
		<%=raw @post.body %>
	</p>
	<% if @post.tag_list.any? %>
	<p class="tags"><span class="glyphicon glyphicon-tags">&nbsp;</span><%=raw @post.tag_list.map { |tag| link_to tag, tag_path(tag) }.join(', ') %></p>
	<% end %>

	<nav>
	  <ul class="pager">
	  	<li class="previous">
			<%= link_to("Previous Post" , @post.previous_post) if @post.previous_post %></li>
	  	<li class="next">
		<%= link_to("Next Post", @post.next_post) if @post.next_post %></li>
		</ul>
	</nav>

	<div id="comments">
		<h3><a id="show-comments">Comments & Amendments ( <%= @post.comments.count %> )</a></h3>
		<%= render @post.comments %>
		<h3>What's on your mind?</h3>
		<br>
		<%= render "comments/form" %>
	</div>
</div>